# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dust3D
tagline:          'Dust3D Blog'
description:      'Devlogs and News about Dust3D'
url:              https://blogs.dust3d.org
baseurl:          /

author:
  name:           'Jeremy HU'
  url:            https://twitter.com/jeremyhu2016

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/huxingyi/dust3d
